### ISSUE TITLE
左上角菜单显示bug

### ISSUE THREAD

**Issue by akkuman** [txperl/Story-for-Typecho#11]
左上角的菜单的#menu-page和.search-box是绝对定位, 如果名字一长就会导致一定的偏移,不太美观,样式图见
![深度截图_选择区域_20180820170348.png](https://i.loli.net/2018/08/20/5b7a8584bbb14.png)
![深度截图_选择区域_20180820170402.png](https://i.loli.net/2018/08/20/5b7a8584bc119.png)

**Comment by Zhang-Siyang** [comment]
Yes，请参见
[修改网站标题后菜单定位](https://github.com/txperl/Story-for-Typecho/blob/master/README.md#%E4%BF%AE%E6%94%B9%E7%BD%91%E7%AB%99%E6%A0%87%E9%A2%98%E5%90%8E%E8%8F%9C%E5%8D%95%E5%AE%9A%E4%BD%8D)

**Comment by txperl** [comment]
是的，这要自已修改的。就是 @Zhang-Siyang 说的那样...

> ##### 修改网站标题后菜单定位
> 若您网站标题字数与原来(5个英文字母)不同，那要自行修改菜单的 `margin` 值。位于 assert/css/main.css 的 `#menu-page(589行处)` 及 `#search-box(609行处) `，每个字符格子宽度为 28px ，可自行计算（别忘了算上菜单格，有4个）。

感觉很多人会忽视这个...之后可能写成自动生成的。

如果还有不清楚请继续回复...

**Comment by akkuman** [comment]
```html
<div class="header-logo">
                <script>
                  var getwbclass = function() {
                    var wbclass = ['b', 'w'];
                    return wbclass[Math.floor(Math.random()*wbclass.length)];
                  }
                  var sitetitle = {{.Site.Title}};
                  for (i in sitetitle) {
                    document.write('<a href="/"><span class="' + getwbclass() + ' titlechar">' + sitetitle.charAt(i) + '</span></a>');
                  }          
                  //setInterval("$('span.titlechar').each(function(i,v){$(this).attr('class', getwbclass()+' titlechar')})",1000);
                </script>
```

**Comment by akkuman** [comment]
自己修正了一下, [https://github.com/akkuman/ink-theme-story/commit/ba89056c36310af9ea2a6f752e34509b46ecd80d](https://github.com/akkuman/ink-theme-story/commit/ba89056c36310af9ea2a6f752e34509b46ecd80d)
