### ISSUE TITLE
第一页会空出三个文章格子

### ISSUE THREAD

**Issue by 99969** [txperl/Story-for-Typecho#16]
你好，作者大大，主题很漂亮现在正在用，发现个问题，不知道是我本地环境还是BUG，就是第一页会空出三个格子，我的站点 [https://www.xiguan.net](https://www.xiguan.net)

**Comment by txperl** [comment]
emm 我看起来很正常啊...可以截下图？

**Comment by 99969** [comment]
> emm 我看起来很正常啊...可以截下图？

已经没问题了，在typecho设置里面有个首页文章设置，设置≥8就行。

**Comment by txperl** [comment]
; )
