### ISSUE TITLE
使用codeblock，第一行对位不整齐

### ISSUE THREAD

**Issue by xhlove** [txperl/Story-for-Typecho#22]
具体见图，强迫症有点难受。。
之前用的模板似乎也会有这个问题，但是在```后面指定编程语言后，就不会第一行多一点，不知道能不能修一下这个问题，thank you~
![Snipaste_2019-10-01_00-34-23.png](https://i.loli.net/2019/10/01/MS8PewhOKEADQi9.png)
![Snipaste_2019-10-01_00-34-36.png](https://i.loli.net/2019/10/01/MNzSYLJ2eVQrAsw.png)

**Comment by xhlove** [comment]
另外希望在图片被放大的时候，如果页面有剩余，可以不完全白色吗？
就像这样还没完全放大，背景的效果。
![Snipaste_2019-10-01_00-40-58.png](https://i.loli.net/2019/10/01/hcdLaj6fpxmzAy7.png)

**Comment by txperl** [comment]
抱歉回复晚了。
关于第一个问题：再下一个版本更新中会解决此问题的。
关于第二个问题：这个可以自行修改 CSS 解决。
