### ISSUE TITLE
不显示文章导航树

### ISSUE THREAD

**Issue by NoverNobida** [txperl/Story-for-Typecho#25]
1. 即使将 `$GLOBALS['isTorTree'] = 'off'; ` 设置为 `$GLOBALS['isTorTree'] = 'on';` 也不能显示导航树；
2. 是否无法代码高亮？

**Comment by txperl** [comment]
1.导航树只支持解析 h3, h4 标题，如有需要请去 `functions.php` 修改。
2.只自带了几种语言支持，要更多请去 prismjs 官网下载。
