### ISSUE TITLE
底端文字悬浮问题

### ISSUE THREAD

**Issue by xhlove** [txperl/Story-for-Typecho#27]
可能这个请求有点过分。

问题：使用DPlayer后`© 2020 Review The World. Using Typecho & Story.`这一行字会悬浮在文章正文中，[链接](https://review.weimo.info/archives/13/)。

![示意图](http://puui.qpic.cn/vshpic/0/HP-XVNA_Gv7gGWtfwze6jYDsvsYk1rdF36aRSihtUsDtjDph_0/0)
这个多半是DPlayer引起的，DPlayer在其他主题也会有些奇奇怪怪的问题。。不过还是想问一下这个有没有什么办法解决...

**Comment by txperl** [comment]
我这边没有复现...但这个问题之前有注意过，是因为 `footerPosition()` 函数引起的。我先提供一个解决办法吧。

最简单的是把 https://github.com/txperl/Story-for-Typecho/blob/master/footer.php#L117 这行代码改成：

```javascript
var winImgNum = document.getElementsByClassName("post-content")[0].getElementsByTagName("img").length + document.getElementsByClassName("post-content")[0].getElementsByTagName("video").length;
``` 

你可以试试？这样应该就能解决了。

**Comment by xhlove** [comment]
看起来是我版本太老的缘故（19/05/19），替换到新版本后没有这个问题了，感谢。
