### ISSUE TITLE
希望添加一个自定义首页文章封面的功能

### ISSUE THREAD

**Issue by ShaoPak** [txperl/Story-for-Typecho#29]

**Comment by ShaoPak** [comment]
大佬的主题很简洁，很喜欢，但感觉首页文章多了后很单调，也不好找文章，希望可以添加首页文章封面

**Comment by txperl** [comment]
文章封面之前尝试过，但如果要美观，对图片的要求比较高。（（

之后我会再试试的。

**Comment by ShaoPak** [comment]
> 文章封面之前尝试过，但如果要美观，对图片的要求比较高。（（
> 
> 之后我会再试试的。

非常期待大佬后续的成果！

**Comment by ShaoPak** [comment]
story在简洁性上太棒了，如果能加上首页文章头图，会更加丰富完美

**Comment by txperl** [comment]
是 [Art Chen](https://github.com/artchen) 大佬设计得好！; )
