### ISSUE TITLE
ios显示时遇到一个问题

### ISSUE THREAD

**Issue by ShaoPak** [txperl/Story-for-Typecho#32]
抱歉，遇到的问题有点多了
系统：ios
设备：iPhone 6s ipad air3
具体描述：文字上边有部分被空白遮挡了，略微放大后文字遮挡现象消失；笔记本上显示正常
![image](https://s1.ax1x.com/2020/08/02/aGLUG4.png)

**Comment by txperl** [comment]
抱歉这个在我这不能复现成功。（（

请问有修改默认字体大小或是默认缩放比例吗？

**Comment by Vndroid** [comment]
建议提供测试链接，以便复现测试。 QaQ

**Comment by txperl** [comment]
@Vndroid ，@ShaoPak 在邮件里已经告诉我测试地址了... 是这个：https://wen.shaopak.com/。

**Comment by ShaoPak** [comment]
> @Vndroid ，@ShaoPak 在邮件里已经告诉我测试地址了... 是这个：[https://wen.shaopak.com/。](https://wen.shaopak.com/%E3%80%82)

大佬抱歉，没注意看邮件，回复有些迟了，ipad和iphone显示都是系统默认比例才有问题，并且安卓显示正常

**Comment by ShaoPak** [comment]
目前版本显示正常了
