### ISSUE TITLE
大佬，目前文章图右边裁剪正常，但是左边裁剪还有bug

### ISSUE THREAD

**Issue by ShaoPak** [txperl/Story-for-Typecho#34]
附上图样：
![6341DBF7-AD2E-4420-9377-EF206EFD509E](https://user-images.githubusercontent.com/62377236/89237829-cdea3100-d626-11ea-9260-4904ea0d40d9.jpeg)

这种情况只在手机端单列显示时才有，地址：wen.shaopak.com，大佬抽时间麻烦看一下

**Comment by txperl** [comment]
强制刷新一下，或者清空网站的浏览器缓存后样式应该就正常了。

**Comment by ShaoPak** [comment]
> 强制刷新一下，或者清空网站的浏览器缓存后样式应该就正常了。

正常了，感谢
