### ISSUE TITLE
文章的标题从h1改为h2后，有一行文字显示有遮挡

### ISSUE THREAD

**Issue by ShaoPak** [txperl/Story-for-Typecho#37]
现在的文章标题字体大小为h1，感觉特别大，特别在手机等小尺寸屏幕上，但是改为h2后，文章显示会有一行被遮挡，目前ios会出现这种问题
![D9580191-8047-4AFC-B4EE-E4BFD994DDF7](https://user-images.githubusercontent.com/62377236/89349409-b7a0ab80-d6e0-11ea-9a5d-4e75e0a76699.jpeg)

**Comment by txperl** [comment]
因为这是你自定义后出现的问题，因此我不会在代码上进行修复（但不排除是其他代码间接导致的问题）。

我测试了一下，仅在 Safari 浏览器（macOS、iOS）上复现成功，Chrome、Firefox（macOS）皆不会出现。不知道会不会是 WebKit 渲染的问题...

这里提供一个解决方法：自行调节一下标题标签（h1, h2, ...）的 `line-height` 值。

**Comment by ShaoPak** [comment]
> 因为这是你自定义后出现的问题，因此我不会在代码上进行修复（但不排除是其他代码间接导致的问题）。
> 
> 我测试了一下，仅在 Safari 浏览器（macOS、iOS）上复现成功，Chrome、Firefox（macOS）皆不会出现。不知道会不会是 WebKit 渲染的问题...
> 
> 这里提供一个解决方法：自行调节一下标题标签（h1, h2, ...）的 `line-height` 值。

大佬，麻烦推荐一个line-height值，我在main.css的h1、h2…下修改了几个line-height值，但是没反应

**Comment by ShaoPak** [comment]
已解决
