### ISSUE TITLE
希望得到一个主题配置页面

### ISSUE THREAD

**Issue by D-Myself** [txperl/Story-for-Typecho#38]
这样可以减少很多工作和方便很多小白，省了很多事，必要时可以付费，希望可以解决一下

**Comment by D-Myself** [comment]
毕竟都一个一个登陆服务器改很慢，在主题后面配置就方便很多

**Comment by Twor** [comment]
可以参考 https://github.com/Twor/Story-for-Typecho/tree/txperl

已经提交PR了

**Comment by txperl** [comment]
可以直接在 Typecho 后台修改配置文件的。

如果一定想要有配置页，可以参考 #28 #36。
