### ISSUE TITLE
评论框需要优化

### ISSUE THREAD

**Issue by ShaoPak** [txperl/Story-for-Typecho#39]
![7AFBFBC5-A31E-4A28-980D-856B137EC9B0](https://user-images.githubusercontent.com/62377236/90315300-efafb600-df4c-11ea-95c6-a203b60c34fe.jpeg)
评论框需要优化，手机端博主登录后依旧和游客一样个人信息占3行，就会有很大的空白区域，体验效果不太好

**Comment by hofaeair** [comment]
电脑端这个问题不是很明显，但看到这个之后，仔细观察了一下，确实有相同的问题。

**Comment by hofaeair** [comment]
其实不影响，游客不会出现这种情况

**Comment by hofaeair** [comment]
电脑端的空位把main.css，543行的50px改成35px就好了

**Comment by txperl** [comment]
> 电脑端的空位把main.css，543行的50px改成35px就好了

是的，这是一个我一开始就知道的问题... 但由于只出现在用户登陆后，所以感觉无伤大雅就没有修复了。近期会更新修复的。

**Comment by UTFX0150** [comment]
啊，三年了，终于修复了😂

**Comment by UTFX0150** [comment]
> 啊，三年了，终于修复了😂

应该说是彻底修复了

**Comment by txperl** [comment]
> 啊，三年了，终于修复了😂

不容易😂。
