### ISSUE TITLE
关于添加备案号的字体设置问题

### ISSUE THREAD

**Issue by EIVX** [txperl/Story-for-Typecho#4]
非常喜欢你的主题，由于我的主机位于国内，这意味着我必须在网页底部添加我的备案号，但是我修改`footer.php`文件并在其中`div`中添加`<p>`标签并添加我的备案号，但是这个主题好看的字体却没有应用到`<p>`标签中的内容，所以我该怎么做才可以使这个博客独特的字体样式应用到我的`<p>`标签中呢。

再次感谢你所做的工作。

**Comment by txperl** [comment]
1.那就不要写在 <p> 标签中
2.自行添加 class p 或相应的 font-family

**Comment by EIVX** [comment]
非常感谢，还有最后一个问题，网站的favicon图标应该怎么设置

**Comment by txperl** [comment]
站点 favicon 图标在没有特别说明的情况下默认显示根目录下的图标。
也就是说，你只要把你的 favicon 图标放在你网站的根目录即可，但注意，必须命名为 favicon 。
不过你也可以在 header 中加入 `<link rel="icon" href="favicon.ico" />` ，href 中填入你的图标地址。

**Comment by EIVX** [comment]
感谢你解决了我的全部问题
