### ISSUE TITLE
首页只显示5篇文章

### ISSUE THREAD

**Issue by hofaeair** [txperl/Story-for-Typecho#40]
typecho默认是5篇，这样会导致首页显示不完整
functions.php里缺少设置：
function themeInit($archive) {
if ($archive->is('index')) {
$archive->parameter->pageSize = 8;
}
}

**Comment by txperl** [comment]
首页文章数量是由 Typecho 设置控制的：设置-阅读-每页文章数目。因此不需要新增额外配置项来设定。

不过即便设置成偶数，在某些布局下仍然可能出现文章格子落单的情况，近期会改改的。

**Comment by hofaeair** [comment]
这样，我没发现这个功能，抱歉

**Comment by hofaeair** [comment]
建议在主题食用里加一下这个内容
