### ISSUE TITLE
默认的baomitu托管稳定性欠佳

### ISSUE THREAD

**Issue by hofaeair** [txperl/Story-for-Typecho#41]
经常无法正常打开，断一下断一下
https://lib.baomitu.com/jquery/3.3.1/jquery.min.js
这些无法访问会导致网页无法正常使用。
希望可以替换链接，或是直接把文件放到本地。

**Comment by xhlove** [comment]
+1

**Comment by txperl** [comment]
之后会替换的。如果有什么推荐的公益静态资源托管平台还请告知。

**Comment by hofaeair** [comment]
可以在这个仓库加上静态文件的文件夹，然后走jsDelivr
