### ISSUE TITLE
想知道长的很像的Hexo主题是怎么回事？

### ISSUE THREAD

**Issue by jiehua1995** [txperl/Story-for-Typecho#42]
Hi Txperl

我看到Hexo有一个和你的主题长的非常像的主题，不知道是不是同一个人做的？因为都有版权信息，所以想了解一下。

https://github.com/artchen/hexo-theme-element

Best,

**Comment by txperl** [comment]
你好。

Story 的首页样式是参考了您提到的 Hexo 主题 [Element](https://github.com/artchen/hexo-theme-element)，这一点也在 [Story-README](https://github.com/txperl/Story-for-Typecho#%E6%84%9F%E8%B0%A2) 中声明。

同时，在开始主题编写前，我也发送邮件询问过 Element 的作者是否允许引用。作者已知悉并允许了。

**Comment by jiehua1995** [comment]
哦哦，明白啦~~我以为是同一个人哈哈哈。
