### ISSUE TITLE
引用块能加入自定义文字吗？

### ISSUE THREAD

**Issue by YatsukiRenka** [txperl/Story-for-Typecho#43]
首先感谢大佬做了个如此好看的主题(
有个问题，引用块右下角的"#blockquote"字样能在编辑器中自定义文字吗？
或者有什么办法能在引用块里面添加标题之类的吗？

![image](https://user-images.githubusercontent.com/38554950/139526934-452b1207-266a-4dcc-8198-00914828112c.png)
想给这个公式的上方或者下方加个类似“XX公式”这样的东西

**Comment by txperl** [comment]
可以是可以，但可能有使用门槛，比如得加入一个特定语法或者直接编写 HTML。

建议还是在引用块前后加入说明吧，或者直接贴 HTML + CSS 代码，应该也行。

**Comment by YatsukiRenka** [comment]
好的，感谢
