### ISSUE TITLE
文献引用好像无法显示

### ISSUE THREAD

**Issue by YatsukiRenka** [txperl/Story-for-Typecho#44]
用markdown语法写的文献引用
```
[^1]
[^1]:xxx
```
这样的格式
但是显示出来是这样的，无法显示文献内容
```
[^1]
[^1]:[xxx](link)
```
格式改成这样也不行

![image](https://user-images.githubusercontent.com/38554950/141407132-71e0fa7d-7c95-4572-93a3-3e610898d572.png)

**Comment by txperl** [comment]
我这边两种 Markdown 格式下的渲染都没问题，应该不是主题不支持。

需要注意的是，`[^1]:` 后面是需要加一个空格才是正确格式。

```
[^1]
[^1]: xxx
[^1]: [xxx](link)
```

如果这也无效，可以使用其他 Markdown 解释器，Typecho 自带的兼容性有时候可能会不太理想。

**Comment by YatsukiRenka** [comment]
感谢回复，找了个新的 Markdown 解释器后显示正常了，是 Typecho 本身的问题
