### ISSUE TITLE
切换主题时发现提示"您选择的风格不存在"

### ISSUE THREAD

**Issue by Gikkingenhanaya** [txperl/Story-for-Typecho#46]
我上传到网站目录theme下，切换主题时发现提示"您选择的风格不存在",系统CentOS 7.9.2009(Py3.7.9)，php版本7.4，typecho版本 1.2.0
该提示页面地址后缀index.php/action/themes-edit?change=Story-for-Typecho-1.21&_=0fd3e3c941d5ed29edf709c4c31b9ced

**Comment by txperl** [comment]
这不是主题的问题。

应该是 Typecho 主题目录下的文件夹命名问题，建议把 `Story-for-Typecho-1.21` 改成 `Story` 即可。

**Comment by Gikkingenhanaya** [comment]
更改文件名后问题已解决。谢谢
