### ISSUE TITLE
引用块的字体是不是有点小？

### ISSUE THREAD

**Issue by Zhang-Siyang** [txperl/Story-for-Typecho#5]
在[我博客](https://blog.zhangsy.me/2018/06/01/%E4%BD%A0%E7%9A%84%E6%A0%91%E8%8E%93%E6%B4%BE%E6%9C%89%E8%B6%B3%E5%A4%9F%E7%9A%84%E7%94%B5%E5%8A%9B%E4%BE%9B%E5%BA%94%E5%90%97%EF%BC%9F.html)上是这样的：

![](https://i.imgur.com/sIdUQZG.png)

那篇日志的 Markdown 文档如下：

```
---
title: 你的树莓派有足够的电力供应吗？
date: 2018-06-01 20:23:48
tags: [RPi, Raspbian]
---
读到 [Power Requirement of the Pi - Milliways 的回答](https://raspberrypi.stackexchange.com/a/51616)。文末的技术细节提供了这两条指令来检查电源供给情况：

\```      【左侧反斜杠本是没有的，为避免排版混乱加上去的，下一个反斜杠也是】
$ ~ vcgencmd get_throttled	#应该是 throttled=0x0
$ ~ cat /sys/class/leds/led1/brightness	#应该是255
\```

> 好久没有更新博客，回头看看之前写的博文有的也需要删掉或精简。
> 
> > Working on it – Fitz
```

**Comment by txperl** [comment]
这个见仁见智吧...是个很性格化的问题。我觉得还可以，不过你可以按照自已喜好修改 css 文件来修改字体。
