### ISSUE TITLE
一些功能建议

### ISSUE THREAD

**Issue by akiting01** [txperl/Story-for-Typecho#50]
作者大大，你好！

这里是我在使用过程中发现的一些建议：

### 1.夜间模式

本主题是没有夜间模式的（至少在我的环境下是这样的），全靠浏览器的强制反色，希望作者有时间可以完善

### 2.一言
作者的另一个主题 [Moricolor](https://github.com/txperl/Moricolor-for-Typecho) 是有一言的，个人认为这是一个很好的小功能，希望作者可以添加

### 另外，祝作者 新春快乐 ！！！

**Comment by txperl** [comment]
新春快乐～

夜间模式确实是一个缺失的部分，之后会尝试支持的。

我也很喜欢一言这类小功能，但总感觉它不太适合这个主题。你可以自己手动尝试加一下，应该不会太困难的。

**Comment by akiting01** [comment]
好的
