### ISSUE TITLE
[bugs] 抓个虫，菜单栏bug，密码保护样式缺失

### ISSUE THREAD

**Issue by akiting01** [txperl/Story-for-Typecho#51]
作者大大，你好！
以下是我在使用过程中发现的一些bug：

### 1.菜单栏bug
~~当标题文字不等于 5 个字符时，点击菜单栏的 `.` 后点击 `3` （也就是 `menu-3` ）后，出现的搜索栏 `menu-search` 会覆盖原本的 `menu-3` （在等于5个字符时无此bug），望作者可以修复。~~（已解决）

### 3.文章发布页 代码高亮 缺失
这个可能是主题特色（？），请问有方法可以引入代码高亮的样式吗？谢谢作者了。

**Comment by txperl** [comment]
密码保护失效问题会在最近修复的。

Story 是支持代码高亮的，但只包含部分语言。可以在这个文件里查看。

https://github.com/txperl/Story-for-Typecho/blob/master/assert/js/prism.js

此外，需要在 Markdown 代码语法中标记语言才会启用。例如：

```markdown
# ```python
# def hello():
#     print("Hello World")
# ```
具体使用中不包含前置 `#` 符号。
```

**Comment by akiting01** [comment]
好的，谢谢解答！

**Comment by txperl** [comment]
刚刚查看了一下官方文档，发现密码保护功能是无需主题主动适配的。

https://docs.typecho.org/develop/password_protected_contents

我本地也调试了一下。

如果你是在 admin 登录状态下访问密码加密的文章，那系统是不会要求你输入密码的，而是直接展示完整内容，因为你本身就有权限访问。

退出登录后，你就会发现文章需要密码才能访问了。

**Comment by akiting01** [comment]
好的，谢谢解答！
