### ISSUE TITLE
您好，我移植了您的主题到emlog

### ISSUE THREAD

**Issue by UTFX0150** [txperl/Story-for-Typecho#54]
商店发布页：https://www.emlog.net/template/detail/1125
社区发布页：https://emlog.cn/post-873.html
GitHub地址：https://github.com/UTFX0150/emtemp-Story
有空可以看看鸭
对主题有一些微调

**Comment by UTFX0150** [comment]
虽然是一款几年前的主题，但放到现在依旧清新脱俗。

**Comment by txperl** [comment]
哇，谢谢移植，已经在 README 的 Forks 中标注了你的 emlog 版本。

**Comment by txperl** [comment]
> 虽然是一款几年前的主题，但放到现在依旧清新脱俗。

还得是首页的原作者设计得好。；）
