### ISSUE TITLE
当文章不属于任何分类时，post-meta 不能完全消失

### ISSUE THREAD

**Issue by Zhang-Siyang** [txperl/Story-for-Typecho#7]
文章不属于任何分类很难，但有可能发生，比如文章手动导入库中（我最近在写MArkdown导入Typecho的脚本）

模拟图：
![](https://i.imgur.com/T5KrYMp.png)

**Comment by txperl** [comment]
还没...近期会更新的。

**Comment by Zhang-Siyang** [comment]
好耶
