### ISSUE TITLE
请求为RSS设计位置

### ISSUE THREAD

**Issue by Zhang-Siyang** [txperl/Story-for-Typecho#9]
RSS我觉得蛮重要的，所以希望您能给RSS地址一个位置，RSS地址一般为 /feed/ 如 https://blog.zhangsy.me/feed/

我开启了伪静态，地址可能有变

主题很棒，希望继续做下去，简单耐用是最好的赞美

> 不能再接着修仙了，脑袋已经很乱了，我先提完这五个issue再说吧

**Comment by Zhang-Siyang** [comment]
按照我的模糊记忆RSS一般都是放置在右下或右上固定位置，或者在侧边栏里

1. 我觉得放在导航1之下没有预期中的显眼，但想长期关注你博客的人应该也是会翻翻各个菜单的吧
2. 放在导航钮后面是一个可行不是很影响整体性设计的解决方案，但这也暴露出本主题一个特点：左上角长度随播客Title长度变化，而且RSS三个字母只占一个格子不太现实；

> 所以我提出了这个疑问，我想您的设计经验比我丰富

3. 版权那边……我想受关注程度比较低吧

好像把皮球都踢回去了 2333，我有一个大胆的想法：进一步把左上角博客名称精简，留菜单和RSS使用（也可转移到右上角），反正页面底部有作者名字嘛；另一个保守的意见是放在页面底部

**Comment by txperl** [comment]
1. 确实会这样。
2. 如果要放在导航栏中，应该不会用 RSS 三个格子给它。可以只写个 R 或者用图标。
3. 不过一般会订阅你 RSS 的人，应该都比较关注你博客，版权那个地方肯定会看到的，1 也是同理。

不不不，我只是个学生，也没什么设计经验之说的...

不不不，这就是一种思想的交流，很容易给人灵感的。我觉得只留菜单和 RSS 不怎么好...虽说文章导航树可以放在文章中开启，但搜索还是必要的。

我想到一个方法，就是按钮 2 的使用。

在除文章&独立页面中，按钮 2 功能为 RSS 链接。在文章&独立页面中，即为开启导航树。但这样有一定误导性，所以可以用不同的图标代替 2 数字。

还可以这样：按钮 2 干脆就是 RSS 链接，把导航树开启按钮放在文章标题旁边。

**Comment by Zhang-Siyang** [comment]
嗯嗯，我觉得按钮2：
 - 在存档列表(含首页)及独立页面时，设为RSS图形
 - 在文章时，仍为目录树

比较好，你觉得呢？

> 我知道你是学生，但不管怎样也开发了不少主题，比我经历丰富是肯定了啦

**Comment by txperl** [comment]
这样就必须要用图标代替 1,2,3 了...有点舍不得。

**Comment by txperl** [comment]
啊...抱歉回复晚了，近期会更新的。

**Comment by Zhang-Siyang** [comment]
好耶
